#!/usr/bin/env bash
# Ubuntu 24.04: sudo bash setup-hardcore-vm.sh
# 既存 discord-mc-admin と共存する場合も、既存 scripts は上書きしない。
set -Eeuo pipefail
[[ $EUID -eq 0 ]] || { echo 'sudo bash setup-hardcore-vm.sh で実行してください。' >&2; exit 1; }

MC_ROOT="${MC_ROOT:-/minecraft}"
MC_USER="${MC_USER:-minecraft}"
MIN_PORT="${SV_MIN_PORT:-25401}"
MAX_PORT="${SV_MAX_PORT:-25410}"
BOT_SSH_PUBLIC_KEY="${BOT_SSH_PUBLIC_KEY:-}"
MODE="${SETUP_MODE:-}"
[[ "$MIN_PORT" =~ ^[0-9]+$ && "$MAX_PORT" =~ ^[0-9]+$ && "$MIN_PORT" -le "$MAX_PORT" ]] || exit 2

if [[ -z "$MODE" ]]; then
  echo 'セットアップ対象を選択してください:'
  select opt in '既存 discord-mc-admin 環境へ追加' '新しい Minecraft VM を構築'; do
    case "$REPLY" in 1) MODE=existing; break;; 2) MODE=fresh; break;; *) echo '1 または 2 を選択してください。';; esac
  done
fi
[[ "$MODE" == existing || "$MODE" == fresh ]] || { echo 'SETUP_MODE は existing または fresh です。' >&2; exit 2; }

if [[ "$MODE" == fresh ]]; then
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y --no-install-recommends ca-certificates curl openjdk-21-jre-headless python3 screen
  id "$MC_USER" &>/dev/null || useradd --create-home --shell /bin/bash "$MC_USER"
  usermod --shell /bin/bash "$MC_USER"
  if [[ -z "$BOT_SSH_PUBLIC_KEY" ]]; then read -r -p 'ボット実行 PC の SSH 公開鍵を貼り付けてください: ' BOT_SSH_PUBLIC_KEY; fi
  [[ "$BOT_SSH_PUBLIC_KEY" =~ ^ssh-(ed25519|rsa|ecdsa)[[:space:]] ]] || { echo 'SSH 公開鍵の形式が不正です。' >&2; exit 2; }
  install -d -o "$MC_USER" -g "$MC_USER" -m 0700 "/home/$MC_USER/.ssh"
  touch "/home/$MC_USER/.ssh/authorized_keys"
  grep -qxF "$BOT_SSH_PUBLIC_KEY" "/home/$MC_USER/.ssh/authorized_keys" || printf '%s\n' "$BOT_SSH_PUBLIC_KEY" >>"/home/$MC_USER/.ssh/authorized_keys"
  chown "$MC_USER:$MC_USER" "/home/$MC_USER/.ssh/authorized_keys"; chmod 0600 "/home/$MC_USER/.ssh/authorized_keys"
else
  id "$MC_USER" &>/dev/null || { echo "既存ユーザーが見つかりません: $MC_USER" >&2; exit 1; }
  command -v screen >/dev/null || { echo 'screen が必要です。sudo apt-get install screen を実行してください。' >&2; exit 1; }
fi

HC_DIR="$MC_ROOT/scripts/hardcore"
CONFIG_DIR="$MC_ROOT/config"
VOICECHAT_PLUGIN_URL="https://cdn.modrinth.com/data/9eGKb6K1/versions/62MVmInV/voicechat-bukkit-2.6.21.jar"
VOICECHAT_PLUGIN="$CONFIG_DIR/voicechat-bukkit.jar"
VOICECHAT_TEMPLATE="$CONFIG_DIR/voicechat-server.properties"
install -d -o "$MC_USER" -g "$MC_USER" -m 0750 "$MC_ROOT/servers" "$MC_ROOT/backups/hardcore"
install -d -o root -g root -m 0755 "$HC_DIR"
if [[ "$MODE" == existing ]]; then
  for template in server.properties eula.txt spigot.yml stop.sh TEST-25565.service; do
    [[ -f "$CONFIG_DIR/$template" ]] || { echo "既存テンプレートがありません: $CONFIG_DIR/$template" >&2; exit 1; }
  done
else
  install -d -o "$MC_USER" -g "$MC_USER" -m 0750 "$CONFIG_DIR"
  cat >"$CONFIG_DIR/server.properties" <<'EOF'
server-port=25565
gamemode=survival
difficulty=hard
hardcore=false
online-mode=false
enforce-secure-profile=false
enable-rcon=false
EOF
  printf 'eula=false\n' >"$CONFIG_DIR/eula.txt"
  printf '# generated by Paper\n' >"$CONFIG_DIR/spigot.yml"
  cat >"$CONFIG_DIR/stop.sh" <<'EOF'
#!/usr/bin/bash
SCREEN_NAME="TEST-25565"
screen -p 0 -S ${SCREEN_NAME} -X eval 'stuff "stop\015"'
sleep 5s
EOF
  cat >"$CONFIG_DIR/TEST-25565.service" <<EOF
[Unit]
Description=TEST-25565

[Service]
User=$MC_USER
Group=$MC_USER
WorkingDirectory=$MC_ROOT/servers/TEST-25565
ExecStart=$MC_ROOT/servers/TEST-25565/start.sh
ExecStop=$MC_ROOT/servers/TEST-25565/stop.sh
Type=forking
Restart=always

[Install]
WantedBy=multi-user.target
EOF
  chown -R "$MC_USER:$MC_USER" "$CONFIG_DIR"
  chmod 754 "$CONFIG_DIR/stop.sh"
fi

# Keep the Simple Voice Chat plugin and its unmodified configuration template
# outside individual servers. Only VC-enabled Paper servers receive a copy.
command -v curl >/dev/null || { echo 'curl が必要です。' >&2; exit 1; }
if [[ ! -f "$VOICECHAT_PLUGIN" ]]; then
  curl --fail --location --proto '=https' --tlsv1.2 "$VOICECHAT_PLUGIN_URL" -o "$VOICECHAT_PLUGIN"
  chown "$MC_USER:$MC_USER" "$VOICECHAT_PLUGIN"; chmod 0644 "$VOICECHAT_PLUGIN"
fi
if [[ ! -f "$VOICECHAT_TEMPLATE" ]]; then
  cat >"$VOICECHAT_TEMPLATE" <<'EOF'
# Simple Voice Chat server config
port=24401
bind_address=
max_voice_distance=48.0
whisper_distance=24.0
codec=VOIP
mtu_size=1024
tcp_rate_limit=16
keep_alive=1000
enable_groups=true
voice_host=
allow_recording=true
spectator_interaction=false
spectator_player_possession=false
force_voice_chat=false
login_timeout=10000
broadcast_range=-1.0
allow_pings=true
EOF
  chown "$MC_USER:$MC_USER" "$VOICECHAT_TEMPLATE"; chmod 0644 "$VOICECHAT_TEMPLATE"
fi

cat >"$HC_DIR/create.sh" <<'CREATE'
#!/usr/bin/env bash
set -Eeuo pipefail
source /etc/default/hardcore-pool-admin
[[ $EUID -eq 0 ]] || exit 1
port="${1:-}"; type="${2:-}"; version="${3:-}"; paper_url="${4:-}"; voice_enabled="${5:-0}"
[[ "$port" =~ ^[0-9]+$ && "$port" -ge "$SV_MIN_PORT" && "$port" -le "$SV_MAX_PORT" ]] || exit 2
[[ "$type" =~ ^(vanilla|paper)$ && "$version" =~ ^[0-9.]+$ ]] || exit 2
[[ "$voice_enabled" =~ ^[01]$ ]] || exit 2
dir="$MC_ROOT/servers/HC-$port"; service="HC-$port.service"
config_dir="$MC_ROOT/config"
[[ ! -e "$dir" ]] || { echo '同じポートのサーバーが既にあります。' >&2; exit 1; }
install -d -o "$MC_USER" -g "$MC_USER" -m 0750 "$dir"
if [[ "$type" == paper ]]; then
  [[ "$paper_url" =~ ^https:// ]] || exit 2
  curl --fail --location --proto '=https' --tlsv1.2 "$paper_url" -o "$dir/$version.jar"
else
  export MC_VERSION="$version" MC_DEST="$dir/$version.jar"
  python3 - <<'PY'
import json, os, urllib.request
with urllib.request.urlopen('https://piston-meta.mojang.com/mc/game/version_manifest_v2.json', timeout=30) as r: manifest=json.load(r)
entry=next((x for x in manifest['versions'] if x['id']==os.environ['MC_VERSION']),None)
if entry is None: raise SystemExit('指定 Vanilla バージョンが見つかりません')
with urllib.request.urlopen(entry['url'], timeout=30) as r: metadata=json.load(r)
urllib.request.urlretrieve(metadata['downloads']['server']['url'],os.environ['MC_DEST'])
PY
fi
# discord-mc-admin と同じ config テンプレートを使い、HC 用の値だけ置換する。
cp "$config_dir/server.properties" "$dir/server.properties"
sed -i "s/^server-port=.*/server-port=$port/; s/^hardcore=.*/hardcore=true/; s/^online-mode=.*/online-mode=false/; s/^enforce-secure-profile=.*/enforce-secure-profile=false/" "$dir/server.properties"
grep -q '^online-mode=' "$dir/server.properties" || echo 'online-mode=false' >>"$dir/server.properties"
grep -q '^enforce-secure-profile=' "$dir/server.properties" || echo 'enforce-secure-profile=false' >>"$dir/server.properties"
cp "$config_dir/eula.txt" "$dir/eula.txt"
sed -i 's/^eula=.*/eula=true/' "$dir/eula.txt"
[[ "$type" == paper ]] && cp "$config_dir/spigot.yml" "$dir/spigot.yml"
if [[ "$voice_enabled" == 1 ]]; then
  [[ "$type" == paper && -f "$config_dir/voicechat-bukkit.jar" && -f "$config_dir/voicechat-server.properties" ]] || { echo 'Simple Voice Chat のテンプレートがありません。' >&2; exit 1; }
  voice_port=$((port - 1000))
  install -d -o "$MC_USER" -g "$MC_USER" -m 0750 "$dir/plugins/voicechat"
  install -o "$MC_USER" -g "$MC_USER" -m 0644 "$config_dir/voicechat-bukkit.jar" "$dir/plugins/voicechat-bukkit.jar"
  cp "$config_dir/voicechat-server.properties" "$dir/plugins/voicechat/voicechat-server.properties"
  sed -i "s/^port=.*/port=$voice_port/" "$dir/plugins/voicechat/voicechat-server.properties"
  chown "$MC_USER:$MC_USER" "$dir/plugins/voicechat/voicechat-server.properties"
fi
chown -R "$MC_USER:$MC_USER" "$dir"
chmod 754 "$dir/$version.jar"
screen_name="HC-$port"
if [[ "${version%%.*}" -ge 26 ]]; then java_bin=/usr/lib/jvm/java-25-openjdk-amd64/bin/java
elif [[ "${version#*.}" =~ ^(2[1-9]|[3-9][0-9]) ]]; then java_bin=/usr/lib/jvm/java-21-openjdk-amd64/bin/java
elif [[ "${version#*.}" =~ ^(1[8-9]|20) ]]; then java_bin=/usr/lib/jvm/java-17-openjdk-amd64/bin/java
else java_bin=/usr/lib/jvm/java-8-openjdk-amd64/bin/java; fi
printf '#!/bin/bash\n/usr/bin/screen -AdmSU %s %s -Xmx1024M -Xms1024M -jar %s/%s.jar nogui\n' "$screen_name" "$java_bin" "$dir" "$version" >"$dir/start.sh"
cp "$config_dir/stop.sh" "$dir/stop.sh"
sed -i "s/SCREEN_NAME=.*/SCREEN_NAME=\"$screen_name\"/" "$dir/stop.sh"
chmod 754 "$dir/start.sh" "$dir/stop.sh"
# root が生成した start.sh / stop.sh を既存 discord-mc-admin と同じ minecraft 所有にする。
chown "$MC_USER:$MC_USER" "$dir/start.sh" "$dir/stop.sh"
cp "$config_dir/TEST-25565.service" "/etc/systemd/system/$service"
sed -i "s/TEST-25565/HC-$port/g" "/etc/systemd/system/$service"
systemctl daemon-reload
systemctl enable "$service"
systemctl start "$service"
sleep 5s
systemctl is-active --quiet "$service"
CREATE

cat >"$HC_DIR/delete.sh" <<'DELETE'
#!/usr/bin/env bash
set -Eeuo pipefail
source /etc/default/hardcore-pool-admin
[[ $EUID -eq 0 ]] || exit 1
port="${1:-}"
[[ "$port" =~ ^[0-9]+$ && "$port" -ge "$SV_MIN_PORT" && "$port" -le "$SV_MAX_PORT" ]] || exit 2
service="HC-$port.service"; dir="$MC_ROOT/servers/HC-$port"
systemctl disable --now "$service" 2>/dev/null || true
rm -f -- "/etc/systemd/system/$service"
rm -rf -- "$dir"
rm -rf -- "$BACKUP_ROOT/HC-$port"
systemctl daemon-reload
DELETE

cat >/usr/local/sbin/hardcore-pool-admin <<'ADMIN'
#!/usr/bin/env bash
set -Eeuo pipefail
source /etc/default/hardcore-pool-admin
[[ $EUID -eq 0 ]] || exit 1
action="${1:-}"; port="${2:-}"
prune_server_backups() {
  local backup_dir="$1" retention_days="$2"
  [[ -d "$backup_dir" ]] || return 0
  find "$backup_dir" -mindepth 1 -maxdepth 1 -type d -mtime +"$retention_days" -exec rm -rf -- {} +
  # Keep the 10 newest timestamp directories, even when all are within retention.
  find "$backup_dir" -mindepth 1 -maxdepth 1 -type d -printf '%T@:%p\0' \
    | sort -z -n \
    | head -z -n -10 \
    | cut -z -d: -f2- \
    | xargs -0 -r rm -rf --
}
if [[ "$action" == prune-backups ]]; then
  retention_days="$port"
  [[ "$retention_days" =~ ^[0-9]+$ ]] || exit 2
  # BACKUP_ROOT/HC-<port>/<UTC timestamp>: only timestamp directories are targets.
  for backup_dir in "$BACKUP_ROOT"/HC-*; do prune_server_backups "$backup_dir" "$retention_days"; done
  exit 0
fi
[[ "$action" =~ ^(create|reset|delete|status|op)$ && "$port" =~ ^[0-9]+$ && "$port" -ge "$SV_MIN_PORT" && "$port" -le "$SV_MAX_PORT" ]] || exit 2
dir="$MC_ROOT/servers/HC-$port"; service="HC-$port.service"
case "$action" in
  create) "$HARDCORE_SCRIPTS_DIR/create.sh" "$port" "${3:-}" "${4:-}" "${5:-}" "${6:-0}" ;;
  reset)
    retention_days="${3:-30}"
    [[ "$retention_days" =~ ^[0-9]+$ ]] || exit 2
    stamp="$(date -u +%Y%m%dT%H%M%SZ)"; backup="$BACKUP_ROOT/HC-$port/$stamp"
    install -d -o "$MC_USER" -g "$MC_USER" -m 0750 "$backup"
    systemctl stop "$service"
    for world in world world_nether world_the_end; do [[ -e "$dir/$world" ]] && mv -- "$dir/$world" "$backup/$world"; done
    prune_server_backups "$BACKUP_ROOT/HC-$port" "$retention_days"
    systemctl start "$service"
    ;;
  delete) "$HARDCORE_SCRIPTS_DIR/delete.sh" "$port" ;;
  status) systemctl is-active --quiet "$service" ;;
  op)
    mcid="${3:-}"
    [[ "$mcid" =~ ^[A-Za-z0-9_]{3,16}$ ]] || exit 2
    systemctl is-active --quiet "$service"
    screen -p 0 -S "HC-$port" -X eval "stuff \"op ${mcid}\\015\""
    ;;
esac
ADMIN

cat >/etc/default/hardcore-pool-admin <<EOF
MC_ROOT=$MC_ROOT
MC_USER=$MC_USER
SV_MIN_PORT=$MIN_PORT
SV_MAX_PORT=$MAX_PORT
BACKUP_ROOT=$MC_ROOT/backups/hardcore
HARDCORE_SCRIPTS_DIR=$HC_DIR
EOF
cat >/etc/sudoers.d/hardcore-pool-admin <<EOF
$MC_USER ALL=(root) NOPASSWD: /usr/local/sbin/hardcore-pool-admin *
EOF
cat >/etc/ufw/applications.d/hc-mc-admin <<EOF
[hc-mc-admin]
title=Hardcore Discord-Minecraft-Administrator
description=Hardcore Minecraft server management by discord.py
ports=$MIN_PORT:$MAX_PORT/tcp|$((MIN_PORT - 1000)):$((MAX_PORT - 1000))/udp
EOF
if command -v ufw >/dev/null; then
  ufw allow hc-mc-admin
fi
chmod 0755 "$HC_DIR/create.sh" "$HC_DIR/delete.sh" /usr/local/sbin/hardcore-pool-admin
chmod 0440 /etc/sudoers.d/hardcore-pool-admin
visudo -cf /etc/sudoers.d/hardcore-pool-admin

echo "完了 ($MODE): $HC_DIR を追加しました。既存 /minecraft/scripts の内容は変更していません。"
echo "BungeeCord は 25401-25410 を hc01-hc10 へ転送するよう設定してください。"
echo "UFW プロファイル hc-mc-admin ($MIN_PORT:$MAX_PORT/tcp) を許可しました。UFW の有効化は手動で行ってください。"
